version = 3

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ .UserName }} '
    foreground = '#45F1C2'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = '#0CA0D8'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'agnoster_short'
      max_depth = 4

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#14A5AE'
    powerline_symbol = ''
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = " {{ .Major}}.{{ .Minor}} env: {{ .Venv}} "
    foreground = "#09739E"
    type = "python"
    style = "plain"

    [blocks.segments.properties]
      home_enabled = true

  [[blocks.segments]]
    template = " {{ .Context }} "
    foreground = "#118C94"
    powerline_symbol = ""
    type = "docker"
    style = "plain"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' '
    foreground = '#cd5e42'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = '# '
    foreground = '#CD4277'
    type = 'text'
    style = 'plain'
